version: "3.8"

services:
  ros2_jazzy:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2_jazzy_workspace
    container_name: ros2_jazzy_container
    network_mode: host
    volumes:
      - ./colcon_ws:/workspace/colcon_ws
      - ./confidential:/workspace/confidential
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
    tty: true
    stdin_open: true